// flow-typed signature: 9d6aacc4c5096e3a1696b1f1bd605377
// flow-typed version: <<STUB>>/history_v4.10.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'history' {
  declare module.exports: any;
}
