// flow-typed signature: d33d9df4141144dfc3a9dcdbb199c250
// flow-typed version: <<STUB>>/react-router_v5.1.2/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}
