// flow-typed signature: 6ea5060a21959ffadc9eda115a176e68
// flow-typed version: <<STUB>>/styled-components_v5.0.1/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
